### ISSUE TITLE
Throwing Exception from Isolate

### ISSUE THREAD

**Issue by xErik** [maxim-saplin/isolate_pool#1]
Hello,

Currently, my isolate throws an application exception but this is not `rethrown` to the enclosing thread.

Is it possible to set exception handlers on `IsolatePool` or `PooledJob`?

I checked the API docs but found no hint. I may have overlooked it, though.

Thank you for this package!

**Comment by maxim-saplin** [comment]
Hi, do I get you right that you didn't use the package and the question is exploratory rather than related to an issues in the package?

The package is supposed to bubble up whatever exception might happen in isolates, e.g. there such a code snippet in unit tests:

```
      var thrown = false;
      try {
        await p.scheduleJob(ThrowingNumbersJob(102));
      } catch (_) {
        thrown = true;
      }

      expect(thrown, true);

```
https://github.com/maxim-saplin/isolate_pool_2/blob/53ac5c7925c61661eb011ee5dacb7b4111d11c23/test/isolate_pool_test.dart#L195

Though you are right, it's worth mentioning in the docs.

Should you have problems with exceptions not being rethrown by the package it would be great to have a look at your examople

**Comment by maxim-saplin** [comment]
Great 👍 

I didn't know of the eagerError as well)

BTW, it  ight be reasonable to use try-finally construct to avoid duplicate pool.stop() call.
